### ISSUE TITLE
valuta di. cambiare il nome del package di progetto

### ISSUE THREAD

**Issue by xcesco** [M4TT3O-91/math-server#16]
il nome del package dovrebbe caratterizzare il progetto.

it.units.mathserver

o

it.units.ap.mathserver (ap advanced programming).

cambiarlo anche a livello di maven:

  <groupId>it.units.MatteoFranco.app</groupId>

il groupId dovrebbe coincidere con il package prinicpale

**Comment by M4TT3O-91** [comment]
Rinominato il package in it.units.ap.mathserver, da vedere come fare il rename a livello di maven
