### ISSUE TITLE
ClientThreadLauncher

### ISSUE THREAD

**Issue by xcesco** [M4TT3O-91/math-server#17]
1 - Il logger dovrebbe essere unico a livello di istanza, se non addirittura di classe. Meglio metterlo come field statico (non cambia a seconda dell'istanza della classe, e' sempre quello).

2 - i due try possono essere accorpati.. tanto se qualcosa va male la connessione si chiude in entrambi i casi

**Comment by M4TT3O-91** [comment]
1 - Creato il logger come private static final Logger
2 - Accorpato i due try in uno unico
