### ISSUE TITLE
MathServer

### ISSUE THREAD

**Issue by xcesco** [M4TT3O-91/math-server#18]
1 -  sicuro che se si supera il numero di processori, le richieste devono essere rifiutate (da controllare)?
2 - per come viene usato il nome ClientThreadLauncher non mi convince molto... ClientHandler o ClientThread?

**Comment by M4TT3O-91** [comment]
1 - Nelle specifiche non è riportato il comportamento al superamento dei client massimi servibili (n = n° processori), ASSUMO (da specificare nelPDF) che al superamento delle richieste il client venga informato della coda piena e chiusa la connessione
2 - Corretto il nome come da suggerimento in clientHandler che sta al di sotto di handleClient
