### ISSUE TITLE
InputProcessor

### ISSUE THREAD

**Issue by xcesco** [M4TT3O-91/math-server#19]
1 - le statistiche devono essere incrementate anche un comando e' errato (da verificare)?
2 -  in realta' va bene. Solo per condividere un modo alternativo. Reponse.createErrorResponse(e). Metodo statico che riceve in input eccezione e crea oggetto Response (usando internamente il costruttore). IN questo modo anche nel codice che lo invoca si capisce che si sta generando una risposta d'errore.

**Comment by M4TT3O-91** [comment]
1- Non specificato da specifiche, ne in termini di stampa ne di conteggio
2- Fatto con Response.createErrorResponse(e) che risulta più leggibile de elegante
